on:
  push:
    branches:
      - ros2
jobs:
  build:
    strategy:
        matrix:
          ros_distro: [humble, rolling]
    runs-on: ubuntu-latest      
    steps:
      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: ${{ matrix.ros_distro }}
      - uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: tagslam
          target-ros2-distro: ${{ matrix.ros_distro }}
          vcs-repo-file-url: https://raw.githubusercontent.com/Sid220/tagslam/refs/heads/ros2/tagslam.repos
