name: ROS Build
on: [push]
jobs:
  build_docker:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:focal
    steps:
      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: noetic
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: "sudo apt install software-properties-common python3-vcstool python3-catkin-tools python3-osrf-pycommon -y && sudo apt-add-repository ppa:borglab/gtsam-release-4.1 && sudo apt update && sudo apt install libgtsam-dev libgtsam-unstable-dev -y"
        shell: bash
      - run: "source /opt/ros/noetic/setup.bash && catkin_make"
        shell: bash
